services:
  api:
    build: ./API
    container_name: macuin_fastapi
    ports: 
      - "15001:5000"
    volumes:
      - ./API/app:/app/app

  flask:
    build: ./Cliente_Flask
    container_name: cliente_flask
    ports: 
      - "15002:5000"
    volumes:
      - ./Cliente_Flask/app:/app/app

  laravel:
    build: ./Cliente_Laravel
    container_name: cliente_laravel
    ports: 
      - "15003:8000"
    volumes:
      - ./Cliente_Laravel:/app